"""SVDocGraph command-line interface.

Designed to feel like ``cargo doc`` / ``mkdocs`` for Bender-based SystemVerilog:
install the tool once, then run it inside any bender project with no arguments and
it discovers everything itself.

  svdocgraph gen [PATH]       generate the docs into ./.svdocgraph
  svdocgraph open [PATH]      open the generated docs (building them if needed)
  svdocgraph serve [PATH]     generate, then serve over http
  svdocgraph init [PATH]      add a svdocgraph.yml and a .gitignore rule
  svdocgraph dump [PATH]      emit the extracted design model as JSON
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
import webbrowser

from . import __version__, bender, deps, extract, project
from .render import render_site

QUIET = False


def _log(msg: str) -> None:
    if not QUIET:
        print(f"\033[36m›\033[0m {msg}", file=sys.stderr)


def _ok(msg: str) -> None:
    if not QUIET:
        print(f"\033[32m✓\033[0m {msg}", file=sys.stderr)


def _warn(msg: str) -> None:
    print(f"\033[33m!\033[0m {msg}", file=sys.stderr)


def _err(msg: str) -> None:
    print(f"\033[31m✗\033[0m {msg}", file=sys.stderr)


# -- shared resolution -----------------------------------------------------


class Ctx:
    """Resolved project root, config and output directory for one invocation."""

    def __init__(self, args, use_output: bool = True):
        self.root, found = project.find_project_root(args.path)
        if not found:
            _warn(f"No Bender.yml found in {os.path.abspath(args.path)} or its parents; "
                  "continuing with that directory as the project root.")
        self.config = project.load_config(self.root)
        # `dump` writes a JSON file, not a site: its -o is not an output directory.
        out = (getattr(args, "output", None) if use_output else None) or self.config.output
        self.outdir = out if os.path.isabs(out) else os.path.join(self.root, out)
        self.outdir = os.path.abspath(self.outdir)
        self.is_default_output = not use_output or getattr(args, "output", None) is None
        self.tops = list(dict.fromkeys(self.config.tops + (getattr(args, "top", None) or [])))

    @property
    def rel_out(self) -> str:
        rel = os.path.relpath(self.outdir, os.getcwd())
        return rel if not rel.startswith("..") else self.outdir


def _build_design(ctx: Ctx):
    _log(f"Project: {ctx.root}")
    if ctx.config.found:
        _log(f"Config:  {os.path.relpath(ctx.config.path, ctx.root)}")
    info = bender.collect(ctx.root)
    if info.root_package:
        _log(f"Bender root package: \033[1m{info.root_package}\033[0m "
             f"({len(info.root_files)} source files, {len(info.packages)} deps)")
    else:
        _warn("No bender root package detected (is there a Bender.yml?).")

    with tempfile.TemporaryDirectory() as td:
        cmd_file = bender.write_command_file(info, os.path.join(td, "sources.f")) or ""
        _log("Elaborating with slang …")
        design = extract.extract_design(ctx.root, info, cmd_file, extra_tops=ctx.tops)

    _ok(f"Extracted {len(design.modules)} modules "
        f"({sum(1 for m in design.modules.values() if m.package == design.root_package)} owned), "
        f"{len(design.tops)} tops")
    for d in design.diagnostics[:8]:
        _warn(d)
    return design


def _preflight() -> int:
    """Fail fast on missing external tools, instead of rendering an empty site."""
    for dep in deps.missing_required():
        _err(f"{dep.name}: {dep.detail}")
        if dep.hint:
            for line in dep.hint.splitlines():
                print(f"  {line}", file=sys.stderr)
    if deps.missing_required():
        return 3
    for dep in deps.optional_gaps():
        _warn(f"{dep.name}: {dep.detail}")
        if dep.hint:
            _warn(dep.hint)
    return 0


def _generate(ctx: Ctx, force: bool) -> int:
    """Extract and render. Returns a process exit code."""
    rc = _preflight()
    if rc:
        return rc
    if not force and not project.is_ours(ctx.outdir):
        _err(f"{ctx.rel_out} is not empty and was not generated by SVDocGraph.")
        _err("Refusing to overwrite it. Pass --force, or pick another -o directory.")
        return 2

    design = _build_design(ctx)
    if not design.modules:
        _err("No modules extracted - nothing to render.")
        return 1

    _log(f"Rendering → {ctx.rel_out}")
    render_site(design, ctx.outdir, title=ctx.config.name)

    if ctx.is_default_output:
        touched = project.ensure_gitignored(ctx.outdir)
        if touched:
            _log(f"Added {os.path.basename(ctx.outdir)}/ to "
                 f"{os.path.relpath(touched, os.getcwd())}")

    _ok(f"Docs ready in \033[1m{ctx.rel_out}\033[0m")
    _log(f"Open with: svdocgraph open   ({project.index_url(ctx.outdir)})")
    return 0


def _open_browser(url: str) -> None:
    if not webbrowser.open(url):
        _warn(f"Could not launch a browser. Open this URL manually:\n  {url}")


# -- commands --------------------------------------------------------------


def cmd_gen(args) -> int:
    ctx = Ctx(args)
    rc = _generate(ctx, args.force)
    if rc == 0 and args.open:
        _open_browser(project.index_url(ctx.outdir))
    return rc


def cmd_open(args) -> int:
    ctx = Ctx(args)
    index = os.path.join(ctx.outdir, "index.html")
    if not os.path.isfile(index):
        _log("No docs generated yet - building them first.")
        rc = _generate(ctx, args.force)
        if rc != 0:
            return rc
    else:
        info = project.read_build_info(ctx.outdir) or {}
        when = info.get("generated_at")
        _log(f"Opening {ctx.rel_out}" + (f" (generated {when})" if when else ""))
    _open_browser(project.index_url(ctx.outdir))
    return 0


def cmd_serve(args) -> int:
    import functools
    import http.server
    import socketserver

    ctx = Ctx(args)
    if not args.no_build or not os.path.isfile(os.path.join(ctx.outdir, "index.html")):
        rc = _generate(ctx, args.force)
        if rc != 0:
            return rc

    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=ctx.outdir)
    socketserver.TCPServer.allow_reuse_address = True
    try:
        httpd = socketserver.TCPServer(("", args.port), handler)
    except OSError as exc:
        _err(f"Cannot listen on port {args.port}: {exc}")
        return 1
    with httpd:
        url = f"http://localhost:{args.port}/"
        _ok(f"Serving at \033[1m{url}\033[0m  (Ctrl-C to stop)")
        if args.open:
            _open_browser(url)
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print(file=sys.stderr)
    return 0


def cmd_init(args) -> int:
    root, found = project.find_project_root(args.path)
    if not found:
        _warn(f"No Bender.yml in {os.path.abspath(args.path)} or its parents - "
              "svdocgraph is meant to run from a bender project root.")
    cfg = project.write_config(root)
    if cfg:
        _ok(f"Wrote {os.path.relpath(cfg, os.getcwd())}")
    else:
        _log("Config already exists; left it untouched.")
    touched = project.ensure_gitignored(os.path.join(root, project.DEFAULT_OUTPUT))
    if touched:
        _ok(f"Added {project.DEFAULT_OUTPUT}/ to {os.path.relpath(touched, os.getcwd())}")
    print(
        "\nNext:\n"
        "  svdocgraph gen --open      generate the docs and open them\n"
        "\nTo wire it into a Makefile:\n"
        "  .PHONY: docs\n"
        "  docs:\n"
        "  \tsvdocgraph gen\n",
        file=sys.stderr,
    )
    return 0


def cmd_doctor(args) -> int:
    """Report on everything svdocgraph needs to run."""
    checks = deps.check_all()
    width = max(len(d.name) for d in checks)
    bad = False
    for d in checks:
        mark = "\033[32m✓\033[0m" if d.ok else (
            "\033[31m✗\033[0m" if d.required else "\033[33m!\033[0m")
        print(f"{mark} {d.name.ljust(width)}  {d.detail}")
        if not d.ok:
            bad = bad or d.required
            for line in d.hint.splitlines():
                print(f"  {line}")
    if bad:
        print("\nsvdocgraph cannot run until the items marked ✗ are installed.")
        return 3
    print("\nAll good - run `svdocgraph gen` from a bender project root.")
    return 0


def cmd_dump(args) -> int:
    import json
    rc = _preflight()
    if rc:
        return rc
    ctx = Ctx(args, use_output=False)
    design = _build_design(ctx)
    with open(args.output, "w") as fh:
        json.dump(design.to_json(), fh, indent=2)
    _ok(f"Wrote {args.output}")
    return 0


# -- argument parsing ------------------------------------------------------


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        prog="svdocgraph",
        description="Bender-aware SystemVerilog design map & documentation generator. "
                    "Run it from the root of a bender project.",
    )
    p.add_argument("--version", action="version", version=f"svdocgraph {__version__}")
    p.add_argument("-q", "--quiet", action="store_true", help="only print warnings and errors")
    sub = p.add_subparsers(dest="cmd", required=True)

    def common(sp, output: bool = True):
        # Accept --quiet on either side of the subcommand. SUPPRESS keeps the
        # subparser from resetting a --quiet given before the subcommand.
        sp.add_argument("-q", "--quiet", action="store_true", default=argparse.SUPPRESS,
                        help="only print warnings and errors")
        sp.add_argument("path", nargs="?", default=".",
                        help="project root (default: nearest Bender.yml from here)")
        sp.add_argument("--top", action="append", metavar="NAME",
                        help="extra top module(s) to elaborate (repeatable)")
        if output:
            sp.add_argument("-o", "--output", metavar="DIR",
                            help=f"output directory (default: {project.DEFAULT_OUTPUT}/)")
            sp.add_argument("--force", action="store_true",
                            help="overwrite an output directory not generated by svdocgraph")

    g = sub.add_parser("gen", aliases=["build"], help="generate the documentation")
    common(g)
    g.add_argument("--open", action="store_true", help="open the result in a browser")
    g.set_defaults(func=cmd_gen)

    o = sub.add_parser("open", help="open the generated documentation (builds it if missing)")
    common(o)
    o.set_defaults(func=cmd_open)

    s = sub.add_parser("serve", help="generate, then serve over http")
    common(s)
    s.add_argument("-p", "--port", type=int, default=8080, help="port (default: 8080)")
    s.add_argument("--open", action="store_true", help="open the browser")
    s.add_argument("--no-build", action="store_true", help="serve an existing build as-is")
    s.set_defaults(func=cmd_serve)

    i = sub.add_parser("init", help="write svdocgraph.yml and a .gitignore rule")
    i.add_argument("-q", "--quiet", action="store_true", default=argparse.SUPPRESS,
                   help="only print warnings and errors")
    i.add_argument("path", nargs="?", default=".", help="project root (default: .)")
    i.set_defaults(func=cmd_init)

    doc = sub.add_parser("doctor", help="check bender, Graphviz and pyslang")
    doc.set_defaults(func=cmd_doctor)

    d = sub.add_parser("dump", help="emit the extracted design model as JSON")
    common(d, output=False)
    d.add_argument("-o", "--output", default="svdocgraph.json", help="output JSON file")
    d.set_defaults(func=cmd_dump)

    args = p.parse_args(argv)
    global QUIET
    QUIET = args.quiet
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
